(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a}; 
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var da=ca(this),ea="function"===typeof Symbol&&"symbol"===typeof Symbol("x"),k={},fa={};function t(a,b){var c=fa[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]} 
function u(a,b,c){if(b)a:{var d=a.split(".");a=1===d.length;var e=d[0],f;!a&&e in k?f=k:f=da;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ea&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?ba(k,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===fa[d]&&(a=1E9*Math.random()>>>0,fa[d]=ea?da.Symbol(d):"$jscp$"+a+"$"+d),ba(f,fa[d],{configurable:!0,writable:!0,value:b})))}} 
u("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ba(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b},"es6"); 
u("Symbol.iterator",function(a){if(a)return a;a=(0,k.Symbol)("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=da[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ba(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ha(aa(this))}})}return a},"es6"); 
function ha(a){a={next:a};a[t(k.Symbol,"iterator")]=function(){return this};return a}var ka="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},la;if(ea&&"function"==typeof Object.setPrototypeOf)la=Object.setPrototypeOf;else{var ma;a:{var na={a:!0},oa={};try{oa.__proto__=na;ma=oa.a;break a}catch(a){}ma=!1}la=ma?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var pa=la; 
u("String.prototype.endsWith",function(a){return a?a:function(b,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.endsWith must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.endsWith must not be a regular expression");void 0===c&&(c=this.length);c=Math.max(0,Math.min(c|0,this.length));for(var d=b.length;0<d&&0<c;)if(this[--c]!=b[--d])return!1;return 0>=d}},"es6");u("globalThis",function(a){return a||da},"es_2020"); 
function qa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[t(k.Symbol,"iterator")]=function(){return e};return e}u("Array.prototype.values",function(a){return a?a:function(){return qa(this,function(b,c){return c})}},"es8");u("Array.prototype.keys",function(a){return a?a:function(){return qa(this,function(b){return b})}},"es6"); 
u("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}},"es8");var x=this||self;function ra(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Y=function(d,e,f){for(var g=Array(arguments.length-2),h=2;h<arguments.length;h++)g[h-2]=arguments[h];return b.prototype[e].apply(d,g)}}function sa(a){return a};function ta(a){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a};function y(a){if(Error.captureStackTrace)Error.captureStackTrace(this,y);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))}ra(y,Error);y.prototype.name="CustomError";function ua(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");y.call(this,c+a[d])}ra(ua,y);ua.prototype.name="AssertionError";function A(a,b){this.h=a===va&&b||"";this.i=wa}A.prototype.l=!0;A.prototype.g=function(){return this.h};function xa(a){return a instanceof A&&a.constructor===A&&a.i===wa?a.h:"type_error:Const"}var wa={},va={};var ya=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},za=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var Aa={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var Ba;function Ca(){if(void 0===Ba){var a=null,b=x.trustedTypes;if(b&&b.createPolicy){try{a=b.createPolicy("goog#html",{createHTML:sa,createScript:sa,createScriptURL:sa})}catch(c){x.console&&x.console.error(c.message)}Ba=a}else Ba=a}return Ba};function C(a,b){this.i=b===Fa?a:""}C.prototype.l=!0;C.prototype.g=function(){return this.i.toString()};C.prototype.A=!0;C.prototype.h=function(){return 1};C.prototype.toString=function(){return this.i+""};function Ga(a){return a instanceof C&&a.constructor===C?a.i:"type_error:TrustedResourceUrl"}var Ha=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Fa={};function Ia(a){var b=Ca();a=b?b.createScriptURL(a):a;return new C(a,Fa)} 
function Ja(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};function Ka(a){if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ma,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Na,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Oa,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Pa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Qa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ra,"&#0;"));return a}var Ma=/&/g,Na=/</g,Oa=/>/g,Pa=/"/g,Qa=/'/g,Ra=/\x00/g,La=/[\x00&<>"']/;function D(a,b){this.i=b===Sa?a:""}D.prototype.l=!0;D.prototype.g=function(){return this.i.toString()};D.prototype.A=!0;D.prototype.h=function(){return 1};D.prototype.toString=function(){return this.i.toString()};function Ta(a){return a instanceof D&&a.constructor===D?a.i:"type_error:SafeUrl"}var Ua=/^data:(.*);base64,[a-z0-9+\/]+=*$/i,Va=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i; 
function Wa(a){if(a instanceof D)return a;a="object"==typeof a&&a.l?a.g():String(a);Va.test(a)?a=new D(a,Sa):(a=String(a),a=a.replace(/(%0A|%0D)/g,""),a=a.match(Ua)?new D(a,Sa):null);return a}var Sa={},Xa=new D("about:invalid#zClosurez",Sa);var Ya={};function E(a,b){this.h=b===Ya?a:"";this.l=!0}E.prototype.g=function(){return this.h};E.prototype.toString=function(){return this.h.toString()};var Za=new E("",Ya); 
function $a(a){if(a instanceof D)return'url("'+Ta(a).replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof A)a=xa(a);else{a=String(a);var b=a.replace(ab,"$1").replace(ab,"$1").replace(bb,"url");if(cb.test(b)){if(b=!db.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}b=b&&c&&eb(a)}a=b?fb(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new ua("Value does not allow [{;}], got: %s.",[a]);return a} 
function eb(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b} 
var cb=RegExp("^[-,.\"'%_!#/ a-zA-Z0-9\\[\\]]+$"),bb=RegExp("\\b(url\\([ \t\n]*)('[ -&(-\\[\\]-~]*'|\"[ !#-\\[\\]-~]*\"|[!#-&*-\\[\\]-~]*)([ \t\n]*\\))","g"),ab=RegExp("\\b(calc|cubic-bezier|fit-content|hsl|hsla|linear-gradient|matrix|minmax|radial-gradient|repeat|rgb|rgba|(rotate|scale|translate)(X|Y|Z|3d)?|var)\\([-+*/0-9a-zA-Z.%#\\[\\], ]+\\)","g"),db=/\/\*/; 
function fb(a){return a.replace(bb,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(g,h,l){f=h;return l});b=(Wa(d)||Xa).g();return c+f+b+f+e})};var gb={};function F(a,b,c){this.i=c===gb?a:"";this.J=b;this.l=this.A=!0}F.prototype.h=function(){return this.J};F.prototype.g=function(){return this.i.toString()};F.prototype.toString=function(){return this.i.toString()};function hb(a){return a instanceof F&&a.constructor===F?a.i:"type_error:SafeHtml"}function ib(a){if(a instanceof F)return a;var b="object"==typeof a,c=null;b&&a.A&&(c=a.h());return H(Ka(b&&a.l?a.g():String(a)),c)} 
function jb(a){function b(f){Array.isArray(f)?f.forEach(b):(f=ib(f),e.push(hb(f).toString()),f=f.h(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=ib(kb),d=c.h(),e=[];a.forEach(b);return H(e.join(hb(c).toString()),d)}function lb(a){return jb(Array.prototype.slice.call(arguments))}function H(a,b){var c=Ca();a=c?c.createHTML(a):a;return new F(a,b,gb)} 
var mb=/^[a-zA-Z0-9-]+$/,nb={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},ob={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},kb=new F(x.trustedTypes&&x.trustedTypes.emptyHTML||"",0,gb);/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var pb={};function I(){}function J(a){this.g=a}J.prototype=ka(I.prototype);J.prototype.constructor=J;if(pa)pa(J,I);else for(var K in I)if("prototype"!=K)if(Object.defineProperties){var qb=Object.getOwnPropertyDescriptor(I,K);qb&&Object.defineProperty(J,K,qb)}else J[K]=I[K];J.K=I.prototype;J.prototype.toString=function(){return this.g.toString()};function rb(a){if(a instanceof I)if(a instanceof J)a=a.g;else throw Error("");else a=hb(a);return a};function sb(a,b){a.src=Ga(b);var c;b=(a.ownerDocument&&a.ownerDocument.defaultView||window).document;var d=null===(c=b.querySelector)||void 0===c?void 0:c.call(b,"script[nonce]");(c=d?d.nonce||d.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};function tb(a,b){a.write(rb(b))};function ub(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};function vb(a){vb[" "](a);return a}vb[" "]=function(){};function wb(){var a=document;var b="SCRIPT";"application/xhtml+xml"===a.contentType&&(b=b.toLowerCase());return a.createElement(b)};var xb=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function yb(a){var b=a.match(xb);a=b[5];var c=b[6];b=b[7];var d="";a&&(d+=a);c&&(d+="?"+c);b&&(d+="#"+b);return d}function zb(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1}var Ab=/#|$/; 
function Bb(a,b){var c=a.search(Ab),d=zb(a,0,b,c);if(0>d)return null;var e=a.indexOf("&",d);if(0>e||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.substr(d,e-d).replace(/\+/g," "))}var Cb=/[?&]($|#)/; 
function L(a,b,c){for(var d=a.search(Ab),e=0,f,g=[];0<=(f=zb(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.substr(e));a=g.join("").replace(Cb,"$1");c=null!=c?"="+encodeURIComponent(String(c)):"";(b+=c)?(c=a.indexOf("#"),0>c&&(c=a.length),d=a.indexOf("?"),0>d||d>c?(d=c,e=""):e=a.substring(d+1,c),c=[a.substr(0,d),e,a.substr(c)],a=c[1],c[1]=b?a?a+"&"+b:b:a,b=c[0]+(c[1]?"?"+c[1]:"")+c[2]):b=a;return b};function Db(){if(!k.globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);k.globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}}function Eb(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)}var Gb=ub(function(){return za(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],Fb)||1E-4>Math.random()}),Hb=ub(function(){return Fb("MSIE")}); 
function Fb(a){var b;a:{if(b=x.navigator)if(b=b.userAgent)break a;b=""}return-1!=b.indexOf(a)}function O(a){return/^true$/.test(a)}function Ib(a,b){b=void 0===b?document:b;return b.createElement(String(a).toLowerCase())};var Jb=ta("0.20"),Kb=ta("0.002"),Lb=ta("0.00"),Mb=ta("0.00"),Nb=O("false"),Ob=O("true"),Pb=O("true"),Qb=O("true"),Rb=O("true");var Sb=null;function Tb(){if(null===Sb){Sb="";try{var a="";try{a=x.top.location.hash}catch(c){a=x.location.hash}if(a){var b=a.match(/\bdeid=([\d,]+)/);Sb=b?b[1]:""}}catch(c){}}return Sb} 
function Ub(a,b,c){var d=P;if(c?d.g.hasOwnProperty(c)&&""==d.g[c]:1){var e;e=(e=Tb())?(e=e.match(new RegExp("\\b("+a.join("|")+")\\b")))?e[0]:null:null;if(e)a=e;else a:{if(!Hb()&&!Gb()&&(e=Math.random(),e<b)){e=Db();a=a[Math.floor(e*a.length)];break a}a=null}a&&""!=a&&(c?d.g.hasOwnProperty(c)&&(d.g[c]=a):d.h[a]=!0)}}function Q(a){var b=P;return b.g.hasOwnProperty(a)?b.g[a]:""}function Vb(){var a=P,b=[];Eb(a.h,function(c,d){b.push(d)});Eb(a.g,function(c){""!=c&&b.push(c)});return b};var Wb={P:2,X:13,W:14,T:16,S:17,R:18,O:19},P=null;function Xb(){return!!P&&"592230571"==Q(16)};function Yb(a){return"function"==typeof a}var Zb=Array.isArray;function $b(a,b){if(a&&Zb(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]}function ac(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])};var bc=new function(a,b){this.g=a;this.defaultValue=void 0===b?!1:b}(1933);var R=window,S=document;var cc={};function dc(a){cc.TAGGING=cc.TAGGING||[];cc.TAGGING[a]=!0};function T(a){var b="B";if(a.B&&a.hasOwnProperty(b))return a.B;b=new a;return a.B=b};function ec(){var a={};this.g=function(){var b=bc.g,c=bc.defaultValue;return null!=a[b]?a[b]:c}};var fc=[];function U(){var a={};var b=R.google_tag_data;R.google_tag_data=void 0===b?a:b;a=R.google_tag_data;a.ics||(a.ics={entries:{},set:gc,update:hc,addListener:ic,notifyListeners:jc,active:!1,usedDefault:!1,usedUpdate:!1,accessedDefault:!1,accessedAny:!1,wasSetLate:!1});return a.ics} 
function gc(a,b,c,d,e,f){var g=U();!g.usedDefault&&g.usedUpdate&&(g.wasSetLate=!0);g.usedDefault||!g.accessedDefault&&!g.accessedAny||(g.wasSetLate=!0);g.active=!0;g.usedDefault=!0;if(void 0!=b){var h=g.entries;g=h[a]||{};var l=g.region;c=c&&"string"==typeof c?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();if(""===d||c===e||(c===d?l!==e:!c&&!l)){e=!!(f&&0<f&&void 0===g.update);var m={region:c,initial:"granted"===b,update:g.update,quiet:e};if(""!==d||!1!==g.initial)h[a]=m;e&&R.setTimeout(function(){h[a]=== 
m&&m.quiet&&(m.quiet=!1,kc(a),jc(),dc(2))},f)}}}function hc(a,b){var c=U();c.usedDefault||c.usedUpdate||!c.accessedAny||(c.wasSetLate=!0);c.active=!0;c.usedUpdate=!0;if(void 0!=b){var d=lc(a);c=c.entries;c=c[a]=c[a]||{};c.update="granted"===b;b=lc(a);c.quiet?(c.quiet=!1,kc(a)):b!==d&&kc(a)}}function ic(a,b){fc.push({u:a,G:b})}function kc(a){for(var b=0;b<fc.length;++b){var c=fc[b];Zb(c.u)&&-1!==c.u.indexOf(a)&&(c.F=!0)}} 
function jc(a){for(var b=0;b<fc.length;++b){var c=fc[b];if(c.F){c.F=!1;try{c.G({Z:a})}catch(d){}}}}function lc(a){var b=U();b.accessedAny=!0;a=b.entries[a]||{};return void 0!==a.update?a.update:a.initial}function mc(a){var b=U();b.accessedAny=!0;return!(b.entries[a]||{}).quiet}function nc(){if(!T(ec).g())return!1;var a=U();a.accessedAny=!0;return a.active}function oc(a,b){U().addListener(a,b)} 
function pc(a){function b(){for(var e=0;e<c.length;e++)if(!mc(c[e]))return!0;return!1}var c=["ad_storage"];if(b()){var d=!1;oc(c,function(e){d||b()||(d=!0,a(e))})}else a({})}function qc(a){function b(){for(var e=[],f=0;f<c.length;f++){var g=c[f];!1===lc(g)||d[g]||(e.push(g),d[g]=!0)}return e}var c=["ad_storage"],d={};b().length!==c.length&&oc(c,function(e){var f=b();0<f.length&&(e.u=f,a(e))})};function rc(a,b,c,d){if(tc(d)){d=[];b=String(b||uc()).split(";");for(var e=0;e<b.length;e++){var f=b[e].split("="),g=f[0].replace(/^\s*|\s*$/g,"");g&&g==a&&((f=f.slice(1).join("=").replace(/^\s*|\s*$/g,""))&&c&&(f=decodeURIComponent(f)),d.push(f))}a=d}else a=[];return a}function vc(a,b,c,d){var e=uc(),f=window;"null"!==f.origin&&(f.document.cookie=a);a=uc();return e!=a||void 0!=c&&0<=rc(b,a,!1,d).indexOf(c)} 
function wc(a,b,c){function d(n,q,v){if(null==v)return delete g[q],n;g[q]=v;return n+"; "+q+"="+v}function e(n,q){if(null==q)return delete g[q],n;g[q]=!0;return n+"; "+q}if(tc(c.s)){if(void 0==b)var f=a+"=deleted; expires="+(new Date(0)).toUTCString();else c.encode&&(b=encodeURIComponent(b)),b=xc(b),f=a+"="+b;var g={};f=d(f,"path",c.path);if(c.expires instanceof Date)var h=c.expires.toUTCString();else null!=c.expires&&(h=c.expires);f=d(f,"expires",h);f=d(f,"max-age",c.$);f=d(f,"samesite",c.aa);c.ba&& 
(f=e(f,"secure"));if((h=c.domain)&&"auto"===h.toLowerCase()){h=yc();for(var l=0;l<h.length;++l){var m="none"!==h[l]?h[l]:void 0,p=d(f,"domain",m);p=e(p,c.flags);if(!zc(m,c.path)&&vc(p,a,b,c.s))break}}else h&&"none"!==h.toLowerCase()&&(f=d(f,"domain",h)),f=e(f,c.flags),zc(h,c.path)||vc(f,a,b,c.s)}}function Ac(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");wc(a,b,c)}function xc(a){a&&1200<a.length&&(a=a.substring(0,1200));return a}var Bc=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Cc=/(^|\.)doubleclick\.net$/i; 
function zc(a,b){return Cc.test(window.document.location.hostname)||"/"===b&&Bc.test(a)}function uc(){return"null"!==window.origin?window.document.cookie:""}function yc(){var a=[],b=window.document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(c=b.length-2;0<=c;c--)a.push(b.slice(c).join("."));b=window.document.location.hostname;Cc.test(b)||Bc.test(b)||a.push("none");return a} 
function tc(a){if(!T(ec).g()||!a||!nc())return!0;if(!mc(a))return!1;a=lc(a);return null==a?!0:!!a};function Dc(a,b){var c,d=Number(null!=a.D?a.D:void 0);0!==d&&(c=new Date((b||(new Date(Date.now())).getTime())+1E3*(d||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!0,expires:c}};function Ec(a){var b=[],c=S.cookie.split(";");a=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$");for(var d=0;d<c.length;d++){var e=c[d].match(a);e&&b.push({C:e[1],value:e[2],timestamp:Number(e[2].split(".")[1])||0})}b.sort(function(f,g){return g.timestamp-f.timestamp});return b} 
function Fc(a,b){a=Ec(a);var c={};if(!a||!a.length)return c;for(var d=0;d<a.length;d++){var e=a[d].value.split(".");if(!("1"!==e[0]||b&&3>e.length||!b&&3!==e.length)&&Number(e[1])){c[a[d].C]||(c[a[d].C]=[]);var f={version:e[0],timestamp:1E3*Number(e[1]),j:e[2]};b&&3<e.length&&(f.labels=e.slice(3));c[a[d].C].push(f)}}return c};var Gc=/:[0-9]+$/;function Hc(a,b){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].split("=");if(decodeURIComponent(d[0]).replace(/\+/g," ")===b)return decodeURIComponent(d.slice(1).join("=")).replace(/\+/g," ")}} 
function Ic(a,b){var c="query";if("protocol"===c||"port"===c)a.protocol=Jc(a.protocol)||Jc(R.location.protocol);"port"===c?a.port=String(Number(a.hostname?a.port:R.location.port)||("http"==a.protocol?80:"https"==a.protocol?443:"")):"host"===c&&(a.hostname=(a.hostname||R.location.hostname).replace(Gc,"").toLowerCase());var d=Jc(a.protocol);c&&(c=String(c).toLowerCase());switch(c){case "url_no_fragment":b="";a&&a.href&&(b=a.href.indexOf("#"),b=0>b?a.href:a.href.substr(0,b));a=b;break;case "protocol":a= 
d;break;case "host":a=a.hostname.replace(Gc,"").toLowerCase();break;case "port":a=String(Number(a.port)||("http"==d?80:"https"==d?443:""));break;case "path":a.pathname||a.hostname||dc(1);a="/"==a.pathname.charAt(0)?a.pathname:"/"+a.pathname;a=a.split("/");0<=[].indexOf(a[a.length-1])&&(a[a.length-1]="");a=a.join("/");break;case "query":a=a.search.replace("?","");b&&(a=Hc(a,b));break;case "extension":a=a.pathname.split(".");a=1<a.length?a[a.length-1]:"";a=a.split("/")[0];break;case "fragment":a=a.hash.replace("#", 
"");break;default:a=a&&a.href}return a}function Jc(a){return a?a.replace(":","").toLowerCase():""};var Kc={};var Lc=/^\w+$/,Mc=/^[\w-]+$/,Nc={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"};function V(){if(!T(ec).g()||!nc())return!0;var a=lc("ad_storage");return null==a?!0:!!a}function Oc(a,b){mc("ad_storage")?V()?a():qc(a):b?dc(3):pc(function(){Oc(a,!0)})}function Pc(a){return Qc(a).map(function(b){return b.j})} 
function Qc(a){var b=[];if("null"===R.origin||!S.cookie)return b;a=rc(a,S.cookie,void 0,"ad_storage");if(!a||0==a.length)return b;for(var c={},d=0;d<a.length;c={m:c.m},d++){var e=Rc(a[d]);if(null!=e){var f=e;e=f.version;c.m=f.j;var g=f.timestamp;f=f.labels;var h=$b(b,function(l){return function(m){return m.j===l.m}}(c));h?(h.timestamp=Math.max(h.timestamp,g),h.labels=Sc(h.labels,f||[])):b.push({version:e,j:c.m,timestamp:g,labels:f})}}b.sort(function(l,m){return m.timestamp-l.timestamp});return Tc(b)} 
function Sc(a,b){for(var c={},d=[],e=0;e<a.length;e++)c[a[e]]=!0,d.push(a[e]);for(a=0;a<b.length;a++)c[b[a]]||d.push(b[a]);return d}function Uc(a){return a&&"string"==typeof a&&a.match(Lc)?a:"_gcl"} 
function Vc(){var a=R.location.href,b=S.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||dc(1),c="/"+c);a=b.hostname.replace(Gc,"");var d={href:b.href,protocol:b.protocol,host:b.host,hostname:a,pathname:c,search:b.search,hash:b.hash,port:b.port};b=Ic(d,"gclid");c=Ic(d,"gclsrc");a=Ic(d,"wbraid");var e=Ic(d,"dclid");b&&c&&a||(d=d.hash.replace("#",""),b=b||Hc(d,"gclid"),c=c||Hc(d,"gclsrc"),a=a||Hc(d,"wbraid"));return Wc(b,c,e,a)} 
function Wc(a,b,c,d){function e(g,h){f[h]||(f[h]=[]);f[h].push(g)}var f={};f.gclid=a;f.gclsrc=b;f.dclid=c;void 0!==d&&Mc.test(d)&&(f.gbraid=d,e(d,"gb"));if(void 0!==a&&a.match(Mc))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha")}c&&e(c,"dc");return f}function Xc(){var a={},b=Vc();Oc(function(){Yc(b,!1,a)})} 
function Yc(a,b,c,d,e){function f(n){n=["GCL",p,n];0<e.length&&n.push(e.join("."));return n.join(".")}function g(n,q){if(n=Zc(n,h))Ac(n,q,l),m=!0}c=c||{};e=e||[];var h=Uc(c.prefix);d=d||(new Date(Date.now())).getTime();var l=Dc(c,d);l.s="ad_storage";var m=!1,p=Math.round(d/1E3);a.aw&&g("aw",f(a.aw[0]));a.dc&&g("dc",f(a.dc[0]));a.gf&&g("gf",f(a.gf[0]));a.ha&&g("ha",f(a.ha[0]));a.gp&&g("gp",f(a.gp[0]));if((void 0==Kc.enable_gbraid_cookie_write?0:Kc.enable_gbraid_cookie_write)&&!m&&a.gb){a=a.gb[0];d= 
Zc("gb",h);c=!1;if(!b)for(b=Qc(d),d=0;d<b.length;d++)b[d].j===a&&b[d].labels&&0<b[d].labels.length&&(c=!0);c||g("gb",f(a))}}function Zc(a,b){a=Nc[a];if(void 0!==a)return b+a}function $c(a){return 0!==ad(a.split(".")).length?1E3*(Number(a.split(".")[1])||0):0}function Rc(a){a=ad(a.split("."));return 0===a.length?null:{version:a[0],j:a[2],timestamp:1E3*(Number(a[1])||0),labels:a.slice(3)}}function ad(a){return 3>a.length||"GCL"!==a[0]&&"1"!==a[0]||!/^\d+$/.test(a[1])||!Mc.test(a[2])?[]:a} 
function Tc(a){return a.filter(function(b){return Mc.test(b.j)})}function bd(){var a=["aw"],b={};if("null"!==R.origin){for(var c=Uc(b.prefix),d={},e=0;e<a.length;e++)Nc[a[e]]&&(d[a[e]]=Nc[a[e]]);Oc(function(){ac(d,function(f,g){g=rc(c+g,S.cookie,void 0,"ad_storage");g.sort(function(p,n){return $c(n)-$c(p)});if(g.length){var h=g[0];g=$c(h);var l=0!==ad(h.split(".")).length?h.split(".").slice(3):[],m={};h=0!==ad(h.split(".")).length?h.split(".")[2]:void 0;m[f]=[h];Yc(m,!0,b,g,l)}})})}} 
function cd(a,b,c,d){var e=[];c=c||{};if(!V())return e;var f=Qc(a);if(!f.length)return e;for(var g=0;g<f.length;g++)-1===(f[g].labels||[]).indexOf(b)?e.push(0):e.push(1);if(d)return e;1!==e[0]&&(d=f[0],f=f[0].timestamp,b=[d.version,Math.round(f/1E3),d.j].concat(d.labels||[],[b]).join("."),c=Dc(c,f),c.s="ad_storage",Ac(a,b,c));return e}function dd(a,b){b=Uc(b);a=Zc(a,b);if(!a)return 0;a=Qc(a);for(var c=b=0;c<a.length;c++)b=Math.max(b,a[c].timestamp);return b} 
function ed(a){var b=0,c;for(c in a)for(var d=a[c],e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp));return b};var fd=RegExp("^UA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*(?:%3BUA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*)*$"),gd=/^~?[\w-]+(?:\.~?[\w-]+)*$/,hd=/^\d+\.fls\.doubleclick\.net$/,id=/;gac=([^;?]+)/,jd=/;gacgb=([^;?]+)/,kd=/;gclaw=([^;?]+)/,ld=/;gclgb=([^;?]+)/; 
function md(a,b,c){if(hd.test(a.location.host))return(b=a.location.href.match(c))&&2==b.length&&b[1].match(fd)?decodeURIComponent(b[1]):"";a=[];for(var d in b){c=[];for(var e=b[d],f=0;f<e.length;f++)c.push(e[f].j);a.push(d+":"+c.join(","))}return 0<a.length?a.join(";"):""}function nd(a,b,c,d){var e=V()?Fc("_gac_gb",!0):{},f=[],g=!1,h;for(h in e){var l=cd("_gac_gb_"+h,b,c,d);g=g||0!==l.length&&l.some(function(m){return 1===m});f.push(h+":"+l.join(","))}return{I:g?f.join(";"):"",H:md(a,e,jd)}} 
function od(a,b,c,d){if(hd.test(a.location.host)){if((a=a.location.href.match(d))&&2==a.length&&a[1].match(gd))return[{j:a[1]}]}else return Qc((b||"_gcl")+c);return[]}function pd(a,b){return od(a,b,"_aw",kd).map(function(c){return c.j}).join(".")}function qd(a,b){return od(a,b,"_gb",ld).map(function(c){return c.j}).join(".")}function rd(a){0!==Pc("_gcl_aw").length||a&&0!==Pc(a+"_aw").length||(Xc(),bd())} 
function sd(a,b,c){a=cd((b&&b.prefix||"_gcl")+"_gb",a,b,c);return 0===a.length||a.every(function(d){return 0===d})?"":a.join(".")};function td(a){var b=void 0===b?x:b;var c,d;return(null==(c=b.performance)?void 0:null==(d=c.timing)?void 0:d[a])||0};var ud={U:0,L:1,V:2,N:3,M:4};function vd(){this.g={}}function wd(a,b,c){"number"===typeof c&&0<c&&(a.g[b]=Math.round(c))}function xd(a){var b=T(vd);var c=void 0===c?x:c;c=c.performance;wd(b,a,c&&c.now?c.now():null)}function yd(){function a(){return wd(b,0,td("loadEventStart")-td("navigationStart"))}var b=T(vd);0!=td("loadEventStart")?a():window.addEventListener("load",a)}function zd(){var a=T(vd);return t(Object,"values").call(Object,ud).map(function(b){return[b,a.g[b]||0]})};function Ad(a,b,c){a=Bd(a,!0);if(a[b])return!1;a[b]=[];a[b][0]=c;return!0}function Bd(a,b){var c=a.GooglebQhCsO;c||(c={},b&&(a.GooglebQhCsO=c));return c};var Cd={},Dd=null; 
function Ed(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}a=4;void 0===a&&(a=0);if(!Dd)for(Dd={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Cd[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===Dd[h]&&(Dd[h]=g)}}a=Cd[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=f=0;f<b.length-2;f+=3){var l=b[f],m=b[f+1];h=b[f+2];g=a[l>>2];l=a[(l& 
3)<<4|m>>4];m=a[(m&15)<<2|h>>6];h=a[h&63];c[e++]=g+l+m+h}g=0;h=d;switch(b.length-f){case 2:g=b[f+1],h=a[(g&15)<<2]||d;case 1:b=b[f],c[e]=a[b>>2]+a[(b&3)<<4|g>>4]+h+d}return c.join("")};function Fd(a,b,c,d){var e=Bb(c,"fmt");if(d){var f=Bb(c,"random"),g=Bb(c,"label")||"";if(!f)return!1;f=Ed(decodeURIComponent(g.replace(/\+/g," "))+":"+decodeURIComponent(f.replace(/\+/g," ")));if(!Ad(a,f,d))return!1}e&&4!=e&&(c=L(c,"rfmt",e));c=L(c,"fmt",4);e=wb();sb(e,Ia(c));e.onload=function(){a.google_noFurtherRedirects&&d&&d.call&&(a.google_noFurtherRedirects=null,d())};b.getElementsByTagName("script")[0].parentElement.appendChild(e);return!0};var Gd=O("false");function Hd(){if(Yb(R.__uspapi)){var a="";try{R.__uspapi("getUSPData",1,function(b,c){c&&b&&(b=b.uspString)&&RegExp("^[\\da-zA-Z-]{1,20}$").test(b)&&(a=b)})}catch(b){}return a}};var Id=/^[a-zA-Z0-9_]+$/,Jd=!1,Kd="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_enable_display_cookie_match google_gtag_event_data google_remarketing_only google_conversion_linker google_tag_for_child_directed_treatment google_tag_for_under_age_of_consent google_allow_ad_personalization_signals google_restricted_data_processing google_conversion_items google_conversion_merchant_id google_user_id google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_gtm_url_processor google_conversion_page_url google_conversion_referrer_url google_gtm google_gcl_cookie_prefix google_gcl_cookie_path google_gcl_cookie_flags google_gcl_cookie_domain google_gcl_cookie_max_age_seconds google_read_gcl_cookie_opt_out google_basket_feed_country google_basket_feed_language google_basket_discount google_basket_transaction_type google_additional_conversion_params google_additional_params google_transport_url google_gtm_experiments".split(" "), 
Ld=["google_conversion_first_time","google_conversion_snippets"];function W(a){return null!=a?encodeURIComponent(String(a)):""}function Md(a){if(null!=a){a=String(a).substring(0,512);var b=a.indexOf("#");return-1==b?a:a.substring(0,b)}return""}function X(a,b){b=W(b);return""!=b&&(a=W(a),""!=a)?"&".concat(a,"=",b):""}function Nd(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")} 
function Od(a){if(!a||"object"!=typeof a||"function"==typeof a.join)return"";var b=[],c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];if(d&&"function"===typeof d.join){for(var e=[],f=0;f<d.length;++f){var g=Nd(d[f]);null!=g&&e.push(g)}d=0==e.length?null:e.join(",")}else d=Nd(d);(e=Nd(c))&&null!=d&&b.push(e+"="+d)}return b.join(";")}function Pd(a){return"number"!=typeof a&&"string"!=typeof a?"":W(a.toString())} 
function Qd(a,b){if(b.google_read_gcl_cookie_opt_out||b.google_remarketing_only||b.google_conversion_domain&&(!b.google_gcl_cookie_prefix||!/^_ycl/.test(b.google_gcl_cookie_prefix)))return"";var c="";var d=b.google_gcl_cookie_prefix&&"_gcl"!==b.google_gcl_cookie_prefix&&Id.test(b.google_gcl_cookie_prefix)?b.google_gcl_cookie_prefix:"";var e={};b.google_gcl_cookie_domain&&(e.domain=b.google_gcl_cookie_domain);b.google_gcl_cookie_flags&&(e.flags=b.google_gcl_cookie_flags);null!=b.google_gcl_cookie_max_age_seconds&& 
(e.D=b.google_gcl_cookie_max_age_seconds);b.google_gcl_cookie_path&&(e.path=b.google_gcl_cookie_path);d&&(e.prefix=d);if(Rd(b)&&b.v)var f=void 0===b.o;else hd.test(a.location.host)?f=!(kd.test(a.location.href)||id.test(a.location.href)):(f=Math.max(dd("aw",d),ed(V()?Fc():{})),f=Math.max(dd("gb",d),ed(V()?Fc("_gac_gb",!0):{}))>f);if(f){if(void 0!==b.o)return b.o;c=qd(a,d||void 0);f=b.google_conversion_label;var g=sd(f,e,b.v);c=X("gclgb",c)+(g?X("mcov",g):"");if(d)return b.o=c;d=nd(a,f,e,b.v);a=d.H; 
d=d.I;c+=(a?X("gacgb",a):"")+(d?X("gacmcov",d):"");return b.o=c}if(d)return b=pd(a,d),X("gclaw",b);(b=pd(a))&&(c=X("gclaw",b));b=md(a,V()?Fc():{},id);return c+(b?X("gac",b):"")}function Sd(a){function b(d){try{return decodeURIComponent(d),!0}catch(e){return!1}}a=a?a.title:"";if(void 0==a||""==a)return"";a=encodeURIComponent(a);for(var c=256;!b(a.substr(0,c));)c--;return"&tiba="+a.substr(0,c)} 
function Td(a,b,c,d,e){var f="https://",g="landing"===d.google_conversion_type?"/extclk":"/";switch(e){default:return"";case 2:case 3:var h="googleads.g.doubleclick.net/";var l="pagead/viewthroughconversion/";break;case 1:h="www.google.com/";l="pagead/1p-conversion/";break;case 6:h="www.google.com/";l="ccm/conversion/";break;case 0:h=d.google_conversion_domain||"www.googleadservices.com/";l="pagead/conversion/";break;case 5:h=d.google_conversion_domain||"www.googleadservices.com/";l="ccm/conversion/"; 
break;case 4:h=(h=d.google_gtm_experiments)&&h.apcm?"www.google.com":h&&h.capiorig?d.google_conversion_id+".privacysandbox.googleadservices.com":"www.google.com/";l="pagead/privacysandbox/conversion/";break;case 7:h="googleads.g.doubleclick.net/",l="td/rul/"}Nb&&d.google_transport_url&&(h=d.google_transport_url);"/"!==h[h.length-1]&&(h+="/");if(0===h.indexOf("http://")||0===h.indexOf("https://"))f="";f=[f,h,l,W(d.google_conversion_id),g,"?random=",W(d.google_conversion_time)].join("");g=X("cv",d.google_conversion_js_version); 
h=X("fst",d.google_conversion_first_time);l=X("num",d.google_conversion_snippets);var m=X("fmt",d.google_conversion_format),p=d.google_remarketing_only?X("userId",d.google_user_id):"";var n=d.google_tag_for_child_directed_treatment;n=null==n||0!==n&&1!==n?"":X("tfcd",n);var q=d.google_tag_for_under_age_of_consent;q=null==q||0!==q&&1!==q?"":X("tfua",q);var v=d.google_allow_ad_personalization_signals;v=!1===v?X("npa",1):!0===v?X("npa",0):"";var ia=d.google_restricted_data_processing;ia=Pb?!0===ia?X("rdp", 
1):!1===ia?X("rdp",0):"":"";var ee=X("value",d.google_conversion_value),fe=X("currency_code",d.google_conversion_currency),ge=X("label",d.google_conversion_label),he=X("oid",d.google_conversion_order_id),ie=X("bg",d.google_conversion_color);a:{var z=d.google_conversion_language;if(null!=z){z=z.toString();if(2==z.length){z=X("hl",z);break a}if(5==z.length){z=X("hl",z.substring(0,2))+X("gl",z.substring(3,5));break a}}z=""}var je=X("guid","ON"),ke=!d.google_conversion_domain&&"GooglemKTybQhCsO"in x&& 
"function"==typeof x.GooglemKTybQhCsO?X("resp","GooglemKTybQhCsO"):"",le=X("disvt",d.google_disable_viewthrough),me=X("eid",Vb().join());var ja=d.google_conversion_date;var w=[];if(a){var G=a.screen;G&&(w.push(X("u_h",G.height)),w.push(X("u_w",G.width)),w.push(X("u_ah",G.availHeight)),w.push(X("u_aw",G.availWidth)),w.push(X("u_cd",G.colorDepth)));a.history&&w.push(X("u_his",a.history.length))}ja&&"function"==typeof ja.getTimezoneOffset&&w.push(X("u_tz",-ja.getTimezoneOffset()));b&&("function"==typeof b.javaEnabled&& 
w.push(X("u_java",b.javaEnabled())),b.plugins&&w.push(X("u_nplug",b.plugins.length)),b.mimeTypes&&w.push(X("u_nmime",b.mimeTypes.length)));ja=w.join("");w=X("gtm",d.google_gtm);b=b&&b.sendBeacon?X("sendb","1"):"";G=Ud();var oe=X("ig",/googleadservices\.com/.test("www.googleadservices.com")?1:0);var M=Od(d.google_custom_params);var Da=Od(void 0);M=M.concat(0<M.length&&0<Da.length?";":"",Da);M=""==M?"":"&".concat("data=",encodeURIComponent(M));Da=Qd(c,d);var sc=d.google_conversion_page_url,pe=d.google_conversion_referrer_url, 
Ea="";if(c){if(a.top==a)var r=0;else{var N=a.location.ancestorOrigins;if(N)r=N[N.length-1]==a.location.origin?1:2;else{N=a.top;try{var B;if(B=!!N&&null!=N.location.href)c:{try{vb(N.foo);B=!0;break c}catch(qe){}B=!1}r=B}catch(qe){r=!1}r=r?1:2}}B=sc?sc:1==r?a.top.location.href:a.location.href;Ea+=X("frm",r);Ea+=X("url",Md(B));Ea+=X("ref",Md(pe||c.referrer))}a=[g,h,l,m,p,n,q,v,ia,ee,fe,ge,he,ie,z,je,ke,le,me,ja,w,b,G,oe,M,Da,Ea,Sd(c),Vd(d.google_additional_params),Vd(d.google_remarketing_only?{}:d.google_additional_conversion_params), 
"&hn="+W("www.googleadservices.com"),Wd(a)].join("");c=Tb();a+=0<c.length?"&debug_experiment_id="+c:"";if(!d.google_remarketing_only&&!d.google_conversion_domain){c=[X("mid",d.google_conversion_merchant_id),X("fcntr",d.google_basket_feed_country),X("flng",d.google_basket_feed_language),X("dscnt",d.google_basket_discount),X("bttype",d.google_basket_transaction_type)].join("");if(d)if(r=d.google_conversion_items){B=[];g=0;for(h=r.length;g<h;g++)l=r[g],m=[],l&&(m.push(Pd(l.value)),m.push(Pd(l.quantity)),m.push(Pd(l.item_id)), 
m.push(Pd(l.start_date)),m.push(Pd(l.end_date)),B.push("("+m.join("*")+")"));r=0<B.length?"&item="+B.join(""):""}else r="";else r="";c=[a,c,r].join("");a=4E3<c.length?[a,X("item","elngth")].join(""):c}f+=a;1===e||6===e?f+=[X("gcp",1),X("sscte",1),X("ct_cookie_present",1)].join(""):3==e&&(f+=X("gcp",1),f+=X("ct_cookie_present",1));Ob&&(e=Hd(),void 0!==e&&(f+=X("us_privacy",e||"error")));Rd(d)&&(f=d.v?f+X("gbcov",1):f+X("gbcov",0));return f} 
function Xd(a,b,c,d,e,f,g){return'<iframe name="'+a+'"'+(g?' id="'+g+'"':"")+' title="'+b+'" width="'+d+'" height="'+e+'"'+(c?' src="'+c+'"':"")+' frameborder="0" marginwidth="0" marginheight="0" vspace="0" hspace="0" allowtransparency="true"'+(f?' style="display:none"':"")+' scrolling="no"></iframe>'} 
function Yd(a){return{ar:1,bg:1,cs:1,da:1,de:1,el:1,en_AU:1,en_US:1,en_GB:1,es:1,et:1,fi:1,fr:1,hi:1,hr:1,hu:1,id:1,is:1,it:1,iw:1,ja:1,ko:1,lt:1,nl:1,no:1,pl:1,pt_BR:1,pt_PT:1,ro:1,ru:1,sk:1,sl:1,sr:1,sv:1,th:1,tl:1,tr:1,vi:1,zh_CN:1,zh_TW:1}[a]?a+".html":"en_US.html"} 
function Zd(a,b,c,d){function e(h,l,m,p){return'<img height="'+m+'" width="'+l+'" border="0" alt="" src="'+h+'"'+(p?' style="display:none"':"")+" />"}Xb()&&xd(2);var f="";d.google_remarketing_only&&d.google_enable_display_cookie_match&&!Gd&&(P&&Ub(["376635470","376635471"],Jb,2),f=d.google_remarketing_only&&d.google_enable_display_cookie_match&&!Gd&&P&&"376635471"==Q(2)?Xd("google_cookie_match_frame","Google cookie match frame","https://bid.g.doubleclick.net/xbbe/pixel?d=KAE",1,1,!0,null):"");d.google_remarketing_only&& 
!d.google_conversion_domain&&P&&Ub(["759238990","759238991"],Mb,13);!d.google_remarketing_only||d.google_conversion_domain||P&&("759248991"==Q(14)||"759248990"==Q(14))||P&&Ub(["759248990","759248991"],Lb,14);!1!==d.google_conversion_linker&&rd(d.google_gcl_cookie_prefix);b=Td(a,b,c,d,d.google_remarketing_only?2:0);if(0==d.google_conversion_format&&null==d.google_conversion_domain)return'<a href="https://services.google.com/sitestats/'+(Yd(d.google_conversion_language)+"?cid="+W(d.google_conversion_id))+ 
'" target="_blank">'+e(b,135,27,!1)+"</a>"+f;if(void 0!==d.google_conversion_snippets&&1<d.google_conversion_snippets||3==d.google_conversion_format){var g=b;null==d.google_conversion_domain&&(g=3==d.google_conversion_format?b:L(b,"fmt",3));return $d(a,c,d,g)?f:e(g,1,1,!0)+f}g=null;!d.google_conversion_domain&&$d(a,c,d,b)&&(g="goog_conv_iframe",b="");return Xd("google_conversion_frame","Google conversion frame",b,2==d.google_conversion_format?200:300,2==d.google_conversion_format?26:13,!1,g)+f} 
function ae(){return new Image}function $d(a,b,c,d){if(c.google_conversion_domain)return!1;try{return Fd(a,b,d,null)}catch(e){return!1}}function be(a,b){b+=X("async","1");var c=a.google_gtm_url_processor;Yb(c)&&(b=c(b));a=a.opt_image_generator;c=ae;a&&a.call&&(c=a);a=c();a.src=b;a.onload=function(){}} 
function ce(a){if("landing"===a.google_conversion_type||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets="number"===typeof a.google_conversion_snippets&&0<a.google_conversion_snippets?a.google_conversion_snippets+1:1;void 0===a.google_conversion_first_time&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version= 
"9";0!=a.google_conversion_format&&1!=a.google_conversion_format&&2!=a.google_conversion_format&&3!=a.google_conversion_format&&(a.google_conversion_format=3);!1!==a.google_enable_display_cookie_match&&(a.google_enable_display_cookie_match=!0);return!0}function de(a){for(var b=0;b<Kd.length;b++)a[Kd[b]]=null}function ne(a){for(var b={},c=0;c<Kd.length;c++)b[Kd[c]]=a[Kd[c]];for(c=0;c<Ld.length;c++)b[Ld[c]]=a[Ld[c]];return b} 
function Ud(){var a="";Xb()&&(a=zd().map(function(b){return b.join("-")}).join("_"));return X("li",a)}function Wd(a){if(!Qb||!a.__gsaExp||!a.__gsaExp.id)return"";a=a.__gsaExp.id;if(!Yb(a))return"";try{var b=Number(a());return isNaN(b)?"":X("gsaexp",b)}catch(c){return""}}function Vd(a){if(!a)return"";var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=X(c,a[c]));return b}function Rd(a){return(a=a.google_gtm_experiments)&&a.gbcov?!0:!1} 
function re(a,b,c,d){var e;if(e=!d.google_remarketing_only)if(d.google_transport_url||!P||"375603261"!=Q(19)&&"375603260"!=Q(19))e=!1;else{if(!(e=Jd))if(e=t("www.googleadservices.com","endsWith").call("www.googleadservices.com","google.com")?"":"A+sitaPn3hlQ8QipTsncwHz+k1NvfPtFsQqIOiD8GK3M9v9XCeQqlF7x1P9AVJdoYTiJPZXZc5XZYpwc10fH4wEAAACfeyJvcmlnaW4iOiJodHRwczovL3d3dy5nb29nbGVhZHNlcnZpY2VzLmNvbTo0NDMiLCJmZWF0dXJlIjoiQ29udmVyc2lvbk1lYXN1cmVtZW50IiwiZXhwaXJ5IjoxNjQzMTU1MTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlLCJ1c2FnZSI6InN1YnNldCJ9",c.head){var f=Ib("META");c.head.appendChild(f);f.httpEquiv="origin-trial";f.content=e;e=f}else e=null;e?(Jd=!0,e=(e=S.featurePolicy)&&Yb(e.allowsFeature)?e.allowsFeature("attribution-reporting"):!1):e=!1}e&&(e= 
d.google_additional_conversion_params||{},f=d.google_gtm_experiments,e.capi=f&&f.apcm?"2":"1",d.google_additional_conversion_params=e,be(d,Td(a,b,c,d,4)))};var se=!1,te=document.currentScript&&document.currentScript.src||""; 
function ue(a,b,c){try{if(!se&&(se=!0,!c.google_gtm)){var d=void 0,e=Bb(a.location.href,"gtm_debug");ve(e)&&(d=2);d||0!==b.referrer.indexOf("https://tagassistant.google.com/")||(d=3);var f;if(f=!d)f=0<=ya(b.cookie.split("; "),"__TAG_ASSISTANT=x");f&&(d=4);if(!d){var g=b.documentElement.getAttribute("data-tag-assistant-present");ve(g)&&(d=5)}if(d){var h="AW-"+(c.google_conversion_id||"");if(!a["google.tagmanager.debugui2.queue"]){a["google.tagmanager.debugui2.queue"]=[];var l=Ia(xa(new A(va,"https://www.googletagmanager.com/debug/bootstrap"))); 
c={id:h,src:"LEGACY",cond:d};var m=Ha.exec(Ga(l).toString()),p=m[3]||"";var n=Ia(m[1]+Ja("?",m[2]||"",c)+Ja("#",p,void 0));var q=Ib("SCRIPT",b);sb(q,n);var v=b.getElementsByTagName("script")[0];v&&v.parentNode&&v.parentNode.insertBefore(q,v)}a["google.tagmanager.debugui2.queue"].push({messageType:"LEGACY_CONTAINER_STARTING",data:{id:h,scriptSource:te}})}}}catch(ia){}}function ve(a){if(null==a||0===a.length)return!1;a=Number(a);var b=Date.now();return a<b+3E5&&a>b-9E5};function we(a){return a.prerendering?3:{visible:1,hidden:2,prerender:3,preview:4,unloaded:5}[a.visibilityState||a.webkitVisibilityState||a.mozVisibilityState||""]||0}function xe(a){var b;a.visibilityState?b="visibilitychange":a.mozVisibilityState?b="mozvisibilitychange":a.webkitVisibilityState&&(b="webkitvisibilitychange");return b}function ye(a,b){if(3==we(b))return!1;a();return!0} 
function ze(a,b){if(!ye(a,b)){var c=!1,d=xe(b),e=function(){!c&&ye(a,b)&&(c=!0,b.removeEventListener&&b.removeEventListener(d,e,!1))};d&&b.addEventListener&&b.addEventListener(d,e,!1)}};function Ae(a){var b=a.id,c=["id"],d={},e;for(e in a)Object.prototype.hasOwnProperty.call(a,e)&&0>c.indexOf(e)&&(d[e]=a[e]);if(null!=a&&"function"===typeof Object.getOwnPropertySymbols){var f=0;for(e=Object.getOwnPropertySymbols(a);f<e.length;f++)0>c.indexOf(e[f])&&(d[e[f]]=a[e[f]])}if(t(Object,"keys").call(Object,d).length)throw Error("Invalid attribute(s): "+t(Object,"keys").call(Object,d));a={id:b};if(!mb.test("span"))throw Error("");if("SPAN"in ob)throw Error("");c=void 0;b=null;d="";if(a)for(m in a)if(Object.prototype.hasOwnProperty.call(a, 
m)){if(!mb.test(m))throw Error("");var g=a[m];if(null!=g){e=void 0;f=m;if(g instanceof A)g=xa(g);else if("style"==f.toLowerCase()){var h=typeof g;h="object"==h&&null!=g||"function"==h;if(!h)throw Error("");if(!(g instanceof E)){h="";for(e in g)if(Object.prototype.hasOwnProperty.call(g,e)){if(!/^[-_a-zA-Z0-9]+$/.test(e))throw Error("Name allows only [-_a-zA-Z0-9], got: "+e);var l=g[e];null!=l&&(l=Array.isArray(l)?l.map($a).join(" "):$a(l),h+=e+":"+l+";")}g=h?new E(h,Ya):Za}g=g instanceof E&&g.constructor=== 
E?g.h:"type_error:SafeStyle"}else{if(/^on/i.test(f))throw Error("");if(f.toLowerCase()in nb)if(g instanceof C)g=Ga(g).toString();else if(g instanceof D)g=Ta(g);else if("string"===typeof g)g=(Wa(g)||Xa).g();else throw Error("");}g.l&&(g=g.g());e=f+'="'+Ka(String(g))+'"';d+=" "+e}}var m="<span"+d;null==c?c=[]:Array.isArray(c)||(c=[c]);!0===Aa.span?m+=">":(b=lb(c),m+=">"+hb(b).toString()+"</span>",b=b.h());(a=a&&a.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?b=0:b=null);m=H(m,b);var p;m=rb(m).toString();a=null=== 
(p=Ca())||void 0===p?void 0:p.createHTML(m);return new J(null!==a&&void 0!==a?a:m,pb)};P=new function(){var a=[],b=0,c;for(c in Wb)a[b++]=Wb[c];this.h={};this.g={};a=a||[];b=0;for(c=a.length;b<c;++b)this.g[a[b]]=""};Ub(["592230570","592230571"],Kb,16);Xb()&&(xd(1),yd()); 
function Be(a,b,c){function d(m,p){var n=new Image;n.onload=m;n.src=p}function e(){--f;if(0>=f){var m=Bd(a,!1),p=m[b];p&&(delete m[b],(m=p[0])&&m.call&&m())}}var f=c.length+1;if(2==c.length){var g=c[0],h=c[1];0<=zb(g,0,"rmt_tld",g.search(Ab))&&0<=zb(g,0,"ipr",g.search(Ab))&&!h.match(xb)[6]&&(h+=yb(g),c[1]=L(h,"rmt_tld","1"))}for(g=0;g<c.length;g++){h=c[g];var l=Bb(h,"fmt");switch(parseInt(l,10)){case 1:case 2:(l=a.document.getElementById("goog_conv_iframe"))&&!l.src?(l.onload=e,l.src=h):d(e,h);break; 
case 4:Fd(a,a.document,h,e);break;case 5:if(a.navigator&&a.navigator.sendBeacon)if(a.navigator.sendBeacon(h,"")){e();break}else h=L(h,"sendb",2);h=L(h,"fmt",3);default:d(e,h)}}e()}var Ce=["GooglemKTybQhCsO"],Y=x;Ce[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+Ce[0]);for(var Z;Ce.length&&(Z=Ce.shift());)Ce.length||void 0===Be?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=Be; 
(function(a,b,c){if(a){ue(a,c,a);try{if(ce(a)){var d=ne(a);P&&Ub(["375603260","375603261"],Rb?1:0,19);if(3==we(c)){var e="google_conversion_"+Math.floor(1E9*Math.random());tb(c,Ae({id:e}));ze(function(){try{re(a,b,c,d);var f=c.getElementById(e);if(f){var g=H(Zd(a,b,c,d),null);if(void 0!==f.tagName&&null!==f&&void 0!==f.tagName){if("script"===f.tagName.toLowerCase())throw Error("Use setTextContent with a SafeScript.");if("style"===f.tagName.toLowerCase())throw Error("Use setTextContent with a SafeStyleSheet."); 
}f.innerHTML=rb(g)}}catch(h){}},c)}else re(a,b,c,d),tb(c,H(Zd(a,b,c,d),null))}}catch(f){}de(a)}})(window,navigator,document);}).call(this);
